### ISSUE TITLE
Responds with "wrong password" on connect

### ISSUE THREAD

**Issue by finestructure** [JacopoMangiavacchi/M1-Linux-SSH#2]
This looks amazing and I can't wait to play around with it - thanks for creating this project!

I'm having some issues connecting to the vm. Here's what's happening: when connecting to the vm with `ssh 0.0.0.0 -p 2222` I don't get a password prompt but instead it immediately prints `wrong password` on the server side:

```
❯ ./vm-service focal-desktop-arm64.iso vmlinuz initrd --username sas --password letmein
Error: Error Domain=VZErrorDomain Code=2 "Virtualization requires the "com.apple.security.virtualization" entitlement" UserInfo={NSDebugDescription=Virtualization requires the "com.apple.security.virtualization" entitlement}
start on 0.0.0.0 port 2222
wrong password
```

```
❯ ssh 0.0.0.0 -p 2222
The authenticity of host '[0.0.0.0]:2222 ([0.0.0.0]:2222)' can't be established.
ED25519 key fingerprint is SHA256:+Uf0vQCEphq/+560SucQPWkFUKO9WaDzWx/oruqTDxM.
Are you sure you want to continue connecting (yes/no/[fingerprint])? yes
Warning: Permanently added '[0.0.0.0]:2222' (ED25519) to the list of known hosts.
```

I suspect this is due to the host verification prompt. So I tried

```
❯ ssh 0.0.0.0 -p 2222 -o StrictHostKeyChecking=no
Connection to 0.0.0.0 closed by remote host.
Connection to 0.0.0.0 closed.
```

but that crashes the server:

```
wrong password
Assertion failed: file NIO/Selector.swift, line 451
fish: './vm-service focal-desktop-arm6…' terminated by signal SIGILL (Illegal instruction)
```

Avoiding the host verification prompt on first connect has no effect - it also prints `wrong password` on the server side (now leading me to believe that the verification prompt isn't the issue after all).

I'll try to dig around a bit but if you have any pointers, that would be great!

**Comment by JacopoMangiavacchi** [comment]
Are you able to connect if you do not specify --username and --password when starting the service ?

I was thinking to reimplement the authentication providing some sort of SSO with the vm but I'm still not sure how to do it.

**Comment by finestructure** [comment]
I'm afraid not:

```
❯ swift run vm-service ../focal-desktop-arm64.iso ../vmlinuz ../initrd
[3/3] Linking vm-service
Error: Error Domain=VZErrorDomain Code=2 "Virtualization requires the "com.apple.security.virtualization" entitlement" UserInfo={NSDebugDescription=Virtualization requires the "com.apple.security.virtualization" entitlement}
start on 0.0.0.0 port 2222
Precondition failed: unacceptable errno 9 Bad file descriptor in fstat(descriptor:outStat:)): file NIO/System.swift, line 129
fish: 'swift run vm-service ../focal-d…' terminated by signal SIGILL (Illegal instruction)
```

and

```
❯ ssh ubuntu@0.0.0.0 -p 2222 -o StrictHostKeyChecking=no
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@    WARNING: REMOTE HOST IDENTIFICATION HAS CHANGED!     @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
IT IS POSSIBLE THAT SOMEONE IS DOING SOMETHING NASTY!
Someone could be eavesdropping on you right now (man-in-the-middle attack)!
It is also possible that a host key has just been changed.
The fingerprint for the ED25519 key sent by the remote host is
SHA256:443WGcyj56x+q+DO/2VAY+VepYyXQXR4qRlCrMN1Xc0.
Please contact your system administrator.
Add correct host key in /Users/sas/.ssh/known_hosts to get rid of this message.
Offending ED25519 key in /Users/sas/.ssh/known_hosts:36
Password authentication is disabled to avoid man-in-the-middle attacks.
Keyboard-interactive authentication is disabled to avoid man-in-the-middle attacks.
Agent forwarding is disabled to avoid man-in-the-middle attacks.
Connection to 0.0.0.0 closed by remote host.
Connection to 0.0.0.0 closed.
```

I'm pretty sure `ubuntu` is the correct user (no password) as I've booted that same image via this project here and signed in: https://github.com/KhaosT/SimpleVM

**Comment by finestructure** [comment]
I'm probably misunderstanding how this should work: I was assuming this sort of creates a user/pass via the command line arguments on the fly, right? So I'm not sure how to login in the absence of that unless I pick a user that exists in the image.

**Comment by JacopoMangiavacchi** [comment]
At the moment there are different authentications.  The SSL authentication to connect to the service (configurable with the --username and --password command line parameters of the service) and the auth to sign in to the ubuntu host (default is ubuntu and no password).  These are completely separated at the moment and default parameter for the service is to use no username password for ssh.  But as said it should be nice to provide also a SSO option but I still have to figure it out how to do it.

But the real problem I see is that you are building and starting the service using swift run.  Unfortunately in order to use VM api's I needed to provide a special entitlement and I haven't found yet how to pass this entitlement to the swift command line or to the package manager (https://forums.swift.org/t/use-macos-entitlements-with-spm-or-swift-command-line/42230).

You need to build the service with Xcode until we found a way to pass this entitlement.  Xcode project and entitlement are already in the repo.

**Comment by finestructure** [comment]
Ah of course! I'd seen those warnings and then completely forgotten about then 🤪

I'll give that another try tomorrow morning - thanks for your help!

**Comment by finestructure** [comment]
Re: entitlements - that might be a question to ask in the SPM slack.
