### ISSUE TITLE
BUILD FAILED in my mbp m1

### ISSUE THREAD

**Issue by Jackkakaya** [JacopoMangiavacchi/M1-Linux-SSH#4]
** BUILD FAILED **

The following build commands failed:
	CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler
	CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler
(2 failures)

**Comment by mannysz** [comment]
Same here. We're probably missing a requirement.

**Comment by JacopoMangiavacchi** [comment]
Unfortunately you have to build this using Xcode
